# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-14 10:54
from __future__ import unicode_literals

import datetime
import pytz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completion_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='last_modified',
            field=models.DateTimeField(
                default=pytz.utc.localize(datetime.datetime(2018, 2, 14, 10, 54, 48, 964281)),
            ),
            preserve_default=False,
        ),
    ]
