# Generated by Django 3.2.24 on 2024-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completion_aggregator', '0005_cachegroupinvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
