# Generated by Django 4.2 on 2026-01-28
from django.db import migrations, models

import completion_aggregator.models


class Migration(migrations.Migration):

    dependencies = [
        ('completion_aggregator', '0006_rename_index_together_to_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='optional_earned',
            field=models.FloatField(default=0.0, validators=[completion_aggregator.models.validate_positive_float]),
        ),
        migrations.AddField(
            model_name='aggregator',
            name='optional_possible',
            field=models.FloatField(default=0.0, validators=[completion_aggregator.models.validate_positive_float]),
        ),
        migrations.AddField(
            model_name='aggregator',
            name='optional_percent',
            field=models.FloatField(default=1.0, validators=[completion_aggregator.models.validate_percent]),
        ),
    ]
