name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11, 3.12]
        toxenv: [django42, django52, quality, docs]

    steps:
    - name: Start MySQL
      if: contains(matrix.toxenv, 'django')
      run: |
        docker run -d \
          --name mysql \
          -p 3307:3306 \
          -e MYSQL_ROOT_PASSWORD=rootpw \
          mysql:8 \
          --character-set-server=utf8mb4 \
          --collation-server=utf8mb4_unicode_ci


    - name: Wait for MySQL
      if: contains(matrix.toxenv, 'django')
      run: |
        for i in $(seq 1 30); do
          nc -z 127.0.0.1 3307 && echo "MySQL is up!" && exit 0
          echo "Waiting for MySQL... ($i)"
          sleep 2
        done
        echo "MySQL failed to start" && exit 1
      timeout-minutes: 2

    - name: checkout repo
      uses: actions/checkout@v5

    - name: setup python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: make requirements

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Run coverage
      if: matrix.python-version == '3.11' && matrix.toxenv == 'django42'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true
